### ISSUE TITLE
no brew on linux stack

### ISSUE THREAD

**Issue by mryvlin** [bitrise-io/steps-ftp-upload#6]
when running on the linux stack, ftp upload fails with the error message "/tmp/bitrise086566999/step_src/step.sh: line 61: brew: command not found". would be cool if you can fix it asap, as our ci pipeline depends on this step

**Comment by viktorbenei** [comment]
Note for the fix: LFTP is available in apt-get too: http://linoxide.com/linux-how-to/setup-lftp-command-line-ftp/

**Comment by godrei** [comment]
Hi @mryvlin ,
new version of step ([2.0.1](https://github.com/bitrise-io/steps-ftp-upload/releases/tag/2.0.1)) will be available in steplib. 
In this version `Linux` install is fixed.
